### ISSUE TITLE
"Confirm and transfer" button bug with meatmask Rinkeby 

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfer#247]
Using metamask:
Click on confirm and transfer button, metamask will show "1" on the icon, but will not pop up any window.
Manually click on the Metamask icon to bring out pop up window, and confirm the transaction in Metamask. 
Confirm and transfer button will be grey for a second and be back to normal again. and the page will not go  to the next step.

**Comment by timothywangdev** [comment]
Local ngrok cannot reproduce the bug
