### ISSUE TITLE
Better state classification for transfer history

### ISSUE THREAD

**Issue by timothywangdev** [ventureum/Chainsfer#429]
1. sendTxState === 'Pending' => 'SEND_PENDING'
2. sendTxState === 'Confirmed'
   (a) receiveTxState === 'Pending' => 'SEND_CONFIRMED_RECEIVE_PENDING' 
   (b) receiveTxState === 'Confirmed' => 'SEND_CONFIRMED_RECEIVE_CONFIRMED'
   (c) receiveTxState === 'Failed' => 'SEND_CONFIRMED_RECEIVE_FAILURE'
   (d) receiveTxState === null => 'SEND_CONFIRMED_RECEIVE_NOT_INITIATED'
   (d) receiveTxState === null => 'SEND_CONFIRMED_RECEIVE_NOT_INITIATED'
3. sendTxState === 'Confirmed'
   (a) cancelTxState === 'Pending' => 'SEND_CONFIRMED_CANCEL_PENDING' 
   (b) cancelTxState === Confirmed' => 'SEND_CONFIRMED_CANCEL_CONFIRMED'
   (c) cancelTxState === 'Failed' => 'SEND_CONFIRMED_CANCEL_FAILURE'
4. sendTxState === 'Failed' => 'SEND_FAILURE'
5. sendTxState === 'Expired' => 'SEND_EXPIRED'

In the transfer history, show the following

* SEND_PENDING => 'Sending'
* SEND_FAILURE => 'Send Failed'
* SEND_EXPIRED => 'Expired'
* SEND_CONFIRMED_RECEIVE_PENDING => 'Sent'
* SEND_CONFIRMED_RECEIVE_FAILURE => 'Accept Failed'
* SEND_CONFIRMED_RECEIVE_CONFIRMED => 'Accepted'
* SEND_CONFIRMED_RECEIVE_NOT_INITIATED => 'Sent'
* SEND_CONFIRMED_CANCEL_PENDING => 'Cancelling'
* SEND_CONFIRMED_CANCEL_CONFIRMED => 'Cancelled'
* SEND_CONFIRMED_CANCEL_Failure => 'Cancel Failed'

**Comment by williamleha** [comment]
SEND_PENDING => 'Sending' =>  Orange tag (in progress)
SEND_FAILURE => 'Send Failed' => Red tag (error)
SEND_CONFIRMED_RECEIVE_PENDING => 'Sent' =>  Orange tag (in progress)
SEND_CONFIRMED_RECEIVE_FAILURE => 'Accept Failed' =>  Text based
SEND_CONFIRMED_RECEIVE_CONFIRMED => 'Accepted' => Text based
SEND_CONFIRMED_RECEIVE_NOT_INITIATED => 'Sent' =>  Orange tag (in progress)
SEND_CONFIRMED_RECEIVE_EXPIRED => 'Expired' => Red tag (error)
SEND_CONFIRMED_CANCEL_PENDING => 'Cancelling' => Orange tag (in progress)
SEND_CONFIRMED_CANCEL_CONFIRMED => 'Cancelled' =>  Text based 
SEND_CONFIRMED_CANCEL_Failure => 'Cancel Failed' => Red tag (error)
